### ISSUE TITLE
Read + Verify: Machine Reading Comprehension with Unanswerable Questions. Minghao Hu, Furu Wei, Yuxing Peng, Zhen Huang, Nan Yang, and Ming Zhou.

### ISSUE THREAD

**Issue by eva-n27** [thunlp/RCPapers#1]
尊敬的作者，您好。
首先，感谢您收集与整理RC相关的论文。
我在阅读的时候，发现您整理的论文[《Read + Verify: Machine Reading Comprehension with Unanswerable Questions. Minghao Hu, Furu Wei, Yuxing Peng, Zhen Huang, Nan Yang, and Ming Zhou.》](https://arxiv.org/abs/1808.05759)，对应的发表会议或许有点错误，应该是AAAI2019，而不是NAACL2018。

**Comment by qyhfbqz** [comment]
好像是的，你可以提交个pr :smile:

**Comment by Mrlyk423** [comment]
感谢指正！
